### PR TITLE
[FIX] Username as display names for direct messages

### LINKED ISSUE #82: Direct Message Rooms names must be fnames not the usernames
image

### PR DESCRIPTION
**Pull request by dhruvjain99**
image

Fixes #82

### CODE REVIEW

File: client/src/components/CommunityListItem/index.js [hunk 1]
```diff
@@ -1,14 +1,16 @@
...
-        })}
-      </div>
-    );
+  const { community, community_name } = props;
+  return (
+    <div className="community-wrapper">
+      <div className="community-title">{community_name}</div>
+      {community.map((room) => {
+        if (room.open || room.open === undefined)
+          // Here the second condition holds when new room is created as the response from server doesn't return open field on creation
```
Comment (RonLek) [inline client/src/components/CommunityListItem/index.js]: Comments should be above the line they address.

**Review by RonLek — APPROVED** [review]
LGTM! @Sing-Li @murtaza98 please merge this in.

**Review by RonLek — APPROVED** [review]

**Review by murtaza98 — APPROVED** [review]
