### PR TITLE
[FIX] Selectively shows configure webhooks button for signed in repository admins only

### LINKED ISSUE #54: [IMPROVE] Show Config Webhook Button Selectively
Currently the config webhook button is shown all the time when the activity pane is visible. This should be changed to following:

1. Show if user logged in **and** owner of repo corresponding to the channel.
2. Don't show if user in anonymous mode.

### PR DESCRIPTION
**Pull request by RonLek**
Configure webhooks button is displayed when the following two cases are met:
1. The user is signed in AND
2. The signed in user has an admin permission to the repository associated with the current channel.

Closes #54

### CODE REVIEW

File: client/src/components/ActivityPane/index.js [hunk 1]
```diff
@@ -65,6 +73,30 @@ export default function ActivityPane(props) {
...
       })
       .catch((error) => console.log(error));
+
+    try {
+      // Checks if the current user is also the owner of the repo
+      if (authState.user.username) {
+        const repository = props.location.pathname
+          .split("/")[2]
+          .replace("_", "/");
+        const authToken = Cookies.get("gh_private_repo_token")
```
Comment (dhruvjain99) [inline client/src/components/ActivityPane/index.js]: Use || here

**Review by dhruvjain99 — APPROVED** [review]
