### PR TITLE
[FIX] Client side warnings on start

### LINKED ISSUE #69: ESLINT Warnings on running client side code
A list of warnings is generated on running the client-side code on local.

image

### PR DESCRIPTION
**Pull request by dhruvjain99**
Fixes #69

### CODE REVIEW

File: client/src/components/ActivityPane/index.js [hunk 1]
```diff
@@ -74,28 +74,33 @@ export default function ActivityPane(props) {
...
+          setIsRepoOwner(ghRepoResponse.data.permissions.admin);
+        }
+      } catch (error) {
+        console.log(error);
       }
-    } catch (error) {
-      console.log(error);
     }
+    checkIfUserIsOwner();
+    // eslint-disable-next-line
```
Comment (RonLek) [inline client/src/components/ActivityPane/index.js:103]: Instead of disabling lint we should add `webhookSubscriptions` and `authState` to the useEffect dependency array here.

File: client/src/components/ConfigureWebhook/index.js [hunk 2]
```diff
@@ -30,6 +30,7 @@ export default function ConfigureWebhook(props) {
     if (props.webhookId) {
       setSelectedEvents(props.webhookSubscriptions);
     }
+    // eslint-disable-next-line
```
Comment (RonLek) [inline client/src/components/ConfigureWebhook/index.js]: Instead of disabling lint we should add `props.webhookSubscriptions` to the useEffect dependency array here.

**Review by RonLek — CHANGES_REQUESTED** [review]

File: client/src/components/ActivityPane/index.js (hunk 1 above)
Comment (dhruvjain99) [reply client/src/components/ActivityPane/index.js:103]: Adding these will affect the logic.
(We want this hook to run on channel switch. Adding the above dependencies will run it when webhookSubscriptions change)

**Review by RonLek — APPROVED** [review]
lgtm
